# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import festo_pb2 as festo__pb2


class valveControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.openValve = channel.unary_unary(
        '/festo.valveController/openValve',
        request_serializer=festo__pb2.ValveRequest.SerializeToString,
        response_deserializer=festo__pb2.Reply.FromString,
        )
    self.closeValve = channel.unary_unary(
        '/festo.valveController/closeValve',
        request_serializer=festo__pb2.ValveRequest.SerializeToString,
        response_deserializer=festo__pb2.Reply.FromString,
        )


class valveControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def openValve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def closeValve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_valveControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'openValve': grpc.unary_unary_rpc_method_handler(
          servicer.openValve,
          request_deserializer=festo__pb2.ValveRequest.FromString,
          response_serializer=festo__pb2.Reply.SerializeToString,
      ),
      'closeValve': grpc.unary_unary_rpc_method_handler(
          servicer.closeValve,
          request_deserializer=festo__pb2.ValveRequest.FromString,
          response_serializer=festo__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'festo.valveController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
