# default.yaml
# Specifies the upper and lower limits of ur10 joints in the urdf.
# Default limits are 2.0 * pi = 6.2831853 for all joints except
# for elbow_joint. elbow_joint is restricted to +/-pi due to hardware
# limitations.
#
# Limits that align with the robots joint limits (+/- 2*pi) may allow
# joint configurations that lead to protective stop.
# To prevent that we substract a safety tolerance of 0.002.
#
ur10_shoulder_pan_joint:
    lower: -3.7698
    upper: 0.6283
ur10_shoulder_lift_joint:
    lower: -3.141592
    upper: 3.141592
ur10_elbow_joint:
    lower: -3.141592
    upper: 3.141592
ur10_wrist_1_joint:
    lower: -2.094333
    upper: 0.000000
ur10_wrist_2_joint:
    lower: −2.094334
    upper: 2.094333
ur10_wrist_3_joint:
    lower: -0.261791
    upper: 3.490550
