# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_msg_pb2 as image__msg__pb2


class DetectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.detectImage = channel.unary_unary(
        '/image_msg.Detector/detectImage',
        request_serializer=image__msg__pb2.Image.SerializeToString,
        response_deserializer=image__msg__pb2.Detection.FromString,
        )


class DetectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def detectImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'detectImage': grpc.unary_unary_rpc_method_handler(
          servicer.detectImage,
          request_deserializer=image__msg__pb2.Image.FromString,
          response_serializer=image__msg__pb2.Detection.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'image_msg.Detector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
